---

- name: "Install chezmoi"
  become: yes
  ansible.builtin.shell: |
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
  args:
    creates: /usr/local/bin/chezmoi

- name: "Initialize and apply dotfiles"
  ansible.builtin.command: chezmoi init --apply charemma
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/chezmoi"
